globalSkills = ['String', 'I', 'Reason'];

globalWorlds = {
	'#jungleworld': {
		tag: '#jungleworld',
		title: 'Jungle World',
		prefix: 'jungle',
		worldLink: '/jungleworld',
		tutorialLink: '/tutorials#jungleworld',
		difficulty: 'Easy',
		pointsToUnlock: 0,
		pointsToMaster: 125,
		circleId: 'world1Circle',
		creatureId: 'world1CreatureCircle',
		creatureName: 'Panther',
		itemId: 'world1ItemCircle',
		itemName: 'Berry',
		villainId: 'world1VillainCircle',
		villainName: 'Snake',
		dashboardProgressId: 'dashboardJungleProgress',
		dfaActivity: 'River Activity',
		plActivity: 'Table Activity',
		plSkills: globalSkills,
		minDFA: 0.95,
		minPL: 0.95,
		minString: 0.9,
		minI: 0.9,
		minReason: 0.9,
		String: globalSkills[0],
		I: globalSkills[1],
		Reason: globalSkills[2],
	},

	'#oceanworld': {
		tag: '#oceanworld',
		title: 'Ocean World',
		prefix: 'ocean',
		worldLink: '/oceanworld',
		tutorialLink: '/tutorials#oceanworld',
		difficulty: 'Medium',
		pointsToUnlock: 100,
		pointsToMaster: 250,
		circleId: 'world2Circle',
		creatureId: 'world2CreatureCircle',
		creatureName: 'Fish',
		itemId: 'world2ItemCircle',
		itemName: 'Pearl',
		villainId: 'world2VillainCircle',
		villainName: 'Jellyfish',
		dashboardProgressId: 'dashboardOceanProgress',
		dfaActivity: 'Starfish Activity',
		plActivity: 'Net Activity',
		plSkills: globalSkills,
		minDFA: 0.95,
		minPL: 0.95,
		minString: 0.9,
		minI: 0.9,
		minReason: 0.9,
		String: globalSkills[0],
		I: globalSkills[1],
		Reason: globalSkills[2],
	},

	'#iceworld': {
		tag: '#iceworld',
		title: 'Ice World',
		prefix: 'ice',
		worldLink: '/iceworld',
		tutorialLink: '/tutorials#iceworld',
		difficulty: 'Hard',
		pointsToUnlock: 200,
		pointsToMaster: 300,
		circleId: 'world3Circle',
		creatureId: 'world3CreatureCircle',
		creatureName: 'Penguin',
		itemId: 'world3ItemCircle',
		itemName: 'Snowflake',
		villainId: 'world3VillainCircle',
		villainName: 'Killer Whale',
		dashboardProgressId: 'dashboardIceProgress',
		dfaActivity: 'Iceberg Activity',
		plActivity: 'Tower Activity',
		plSkills: globalSkills,
		minDFA: 0.95,
		minPL: 0.95,
		minString: 0.9,
		minI: 0.9,
		minReason: 0.9,
		String: globalSkills[0],
		I: globalSkills[1],
		Reason: globalSkills[2],
	}
};